apiVersion: extensions/v1beta1  
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: gittix.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-svc
              servicePort: 3333
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-svc
              servicePort: 3333
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-svc
              servicePort: 3333
          - path: /?(.*)
            backend:
              serviceName: client-svc
              servicePort: 3000
